// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://wkdugvkkxabtipqfvxcd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndrZHVndmtreGFidGlwcWZ2eGNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MTIyOTksImV4cCI6MjA3MzE4ODI5OX0.1DGL3t1auoCvqHTYoZNLS9SgkWRArxmquggCMwGMPlc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);